### ISSUE TITLE
Update installation documentation 

### ISSUE THREAD

**Issue by kyrylo** [hotwired/strada-android#32]
The "latest version" link leads to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

<img width="422" alt="strada-android:docs:INSTALLATION md at main · hotwired:strada-android 2023-10-17 14-52-11" src="https://github.com/hotwired/strada-android/assets/1079123/618b3fc3-e597-4171-8e9a-43fb75d535b7">

The jcenter reference in Android Studio says it's deprecated:

![Monosnap 2023-10-17 14-53-30](https://github.com/hotwired/strada-android/assets/1079123/859cc38b-c7b4-4c1d-9df4-255e56b334aa)

P.S. I am an Android newbie, so maybe it's obvious what to do for seasoned Android devs, but people like me would be grateful for updated docs 🍻

**Comment by leonvogt** [comment]
Hm I think thath link is outdated. The latest version can viewed at Maven Central: https://central.sonatype.com/artifact/dev.hotwire/strada.    

This works for me:
```gradle
repositories {
    google()
    mavenCentral()
}
```
